version: "3.4"

services:
  postfixadmin-proxy:
    image: mwaeckerlin/postfixadmin-proxy
    build: postfixadmin-proxy
    ports:
      - 8080:8080
    networks:
      - postfixadmin-frontend

  postfixadmin:
    image: mwaeckerlin/postfixadmin
    build: postfixadmin
    environment:
      # setup password is: test123
      # set to anything else to generate a different one, e.g. empty
      SETUP_PASSWORD: 0310f894fb05ed0cf05de3d61abc0ced:c56c4bc25f893e52f6e806a907e30e59edb6e120
      DATABASE_PASSWORD: eepaiph3ohquai2Eilae-change-it
      DEFAULT_ALIASES_ADDRESS: info
      #DEFAULT_ALIASES_DOMAIN: merkur.mrw.sh
      FOOTER_TEXT: "Mailservice Project"
      FOOTER_LINK: "https://github.com/mwaeckerlin/mailservice"
      WELCOME_TEXT: |
        Hi,

        Welcome to your new mail account!
      SHOW_CUSTOM_DOMAINS: "merkur.mrw.sh localhost"
      SHOW_CUSTOM_COLORS: "green red"
    networks:
      postfixadmin-frontend:
        aliases:
          - merkur.mrw.sh
          - merkur
          - demo
          - test
          - lokal
          - extern
      postfixadmin-backend:

  postfixadmin-db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: eepaiph3ohquai2Eilae-change-it
    volumes:
      - type: volume
        source: postfixadmin-db
        target: /usr/lib/mysql
    networks:
      - postfixadmin-backend
      - postfix-backend

  postgrey:
    image: mwaeckerlin/postgrey
    build: postgrey
    networks:
      - greylisting

  smtp-relay:
    image: mwaeckerlin/smtp-relay
    build: smtp-relay

  smtp-relay-tls:
    image: mwaeckerlin/smtp-relay-tls
    build: smtp-relay-tls

  mailforward:
    image: mwaeckerlin/mailforward
    build: mailforward
    environment:
      GREYLIST: "postgrey"
      LOCAL_DOMAINS: "merkur.mrw.sh localhost demo test lokal extern"

  dovecot:
    image: mwaeckerlin/dovecot
    build: dovecot
    ports:
      - "143:143"
      - "993:993"
      - "4190:4190"
    environment:
      DB_NAME: postfixadmin
      DB_USER: postfixadmin
      DB_PASSWORD: eepaiph3ohquai2Eilae-change-it
      DB_HOST: postfixadmin-db
    networks:
      - postfix-backend

  postfix:
    image: mwaeckerlin/postfix
    build: postfix
    ports:
      - "25:25"
      - "587:25"
    environment:
      GREYLIST: "postgrey"
      HOSTNAME: merkur.mrw.sh
      DOMAIN: mrw.sh
      DB_NAME: postfixadmin
      DB_USER: postfixadmin
      DB_PASSWORD: eepaiph3ohquai2Eilae-change-it
      DB_HOST: postfixadmin-db
    networks:
      - postfix-backend
      - greylisting

networks:
  postfixadmin-backend:
  postfixadmin-frontend:
  postfix-backend:
  greylisting:

volumes:
  postfixadmin-db:
