"""PostfixAdmin database schema upgrade (README «Database schema
upgrade after an image update»).

A REAL PostfixAdmin 3.2.4 schema — generated by the old release's own
upgrade chain (fixture rule: derive from the real system, never
hand-write) — sits in the dedicated `postfixadmin-db-upgrade` database.
The CURRENT image runs on top of it. Pinned here:

  1. before: the database carries an old schema-version marker,
  2. the documented trigger — opening setup.php — migrates the schema
     (already on the first unauthenticated GET; the password guards the
     admin-management steps, not the migration),
  3. after: the version marker advanced, and the admin flow that
     depends on the newer schema works (create admin, log in, create a
     domain, open the virtual list — the pages the README names as
     failing with HTTP 500 on a stale schema).
"""
import os

import pymysql
import pytest
from playwright.sync_api import Browser

from conftest import DOMAIN, SETUP_PW, wait_for_http

PA_UP_URL = os.environ.get("POSTFIXADMIN_UPGRADE_URL",
                           "http://postfixadmin-upgrade-proxy:8080")
DB_HOST   = os.environ.get("PA_UPGRADE_DB_HOST", "postfixadmin-db-upgrade")

UPGRADE_ADMIN    = f"upgrade-admin@{DOMAIN}"
UPGRADE_ADMIN_PW = "Upgrade123pass"
UPGRADE_DOMAIN   = "upgrade.local"


def _schema_version() -> int:
    conn = pymysql.connect(host=DB_HOST, user="postfixadmin",
                           password="testpass", database="postfixadmin")
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT value FROM config WHERE name='version'")
            row = cur.fetchone()
            return int(row[0]) if row else 0
    finally:
        conn.close()


def test_schema_upgrade_via_setup(browser: Browser):
    # readiness check via login.php — normal pages never migrate, but a
    # bare GET of setup.php already does (observed: the very first
    # unauthenticated hit runs the migration), so setup.php must not be
    # touched before the old version is recorded
    wait_for_http(f"{PA_UP_URL}/login.php")

    before = _schema_version()
    # the frozen 3.2.4 release chain ends at exactly this marker
    assert before == 1841, (
        f"old-schema seeding is off — expected the 3.2.4 version marker "
        f"1841, found {before} (postfixadmin-old-init broken, or "
        f"something touched setup.php before this test)"
    )

    # the documented trigger: setup.php (authenticated with the setup
    # password) includes upgrade.php and applies the missing steps
    page = browser.new_page()
    page.goto(f"{PA_UP_URL}/setup.php", timeout=30_000)
    page.locator("form[name=authenticate] [name=setup_password]").fill(SETUP_PW)
    page.locator("form[name=authenticate] button[type=submit]").click()
    page.wait_for_load_state("networkidle", timeout=30_000)

    after = _schema_version()
    assert after > before, (
        f"setup.php did not migrate the schema: version stayed at "
        f"{after} (was {before})"
    )

    # the flow that breaks on a stale schema must now work end-to-end
    if page.locator("form[name=create_admin]").count():
        page.locator("form[name=create_admin] [name=setup_password]").fill(SETUP_PW)
        page.locator("form[name=create_admin] [name=username]").fill(UPGRADE_ADMIN)
        page.locator("form[name=create_admin] [name=password]").fill(UPGRADE_ADMIN_PW)
        page.locator("form[name=create_admin] [name=password2]").fill(UPGRADE_ADMIN_PW)
        page.locator("form[name=create_admin] [type=submit]").click()
        page.wait_for_load_state("networkidle", timeout=15_000)

    page.goto(f"{PA_UP_URL}/login.php", timeout=20_000)
    page.locator("[name=fUsername]").fill(UPGRADE_ADMIN)
    page.locator("[name=fPassword]").fill(UPGRADE_ADMIN_PW)
    page.locator("[type=submit]").click()
    page.wait_for_load_state("networkidle", timeout=15_000)

    page.goto(f"{PA_UP_URL}/edit.php?table=domain", timeout=15_000)
    page.locator("[name='value[domain]']").fill(UPGRADE_DOMAIN)
    page.locator("[type=submit]").first.click()
    page.wait_for_load_state("networkidle", timeout=10_000)

    resp = page.goto(f"{PA_UP_URL}/list-virtual.php?domain={UPGRADE_DOMAIN}",
                     timeout=15_000)
    assert resp is not None and resp.status == 200, (
        f"virtual list failed after the schema upgrade "
        f"(HTTP {resp.status if resp else 'no response'}) — the exact "
        f"stale-schema symptom the upgrade must fix"
    )
    assert UPGRADE_DOMAIN in page.content(), (
        "virtual list does not show the domain created after the upgrade"
    )
    page.close()
