Syslog            yes
LogWhy            yes
Canonicalization  relaxed/simple
Mode              sv
SubDomains        no
OversignHeaders   From
SignatureAlgorithm rsa-sha256
Socket            inet:10026@0.0.0.0
PidFile           /run/opendkim/opendkim.pid
KeyTable          /etc/opendkim/KeyTable
SigningTable      refile:/etc/opendkim/SigningTable
ExternalIgnoreList refile:/etc/opendkim/TrustedHosts
InternalHosts     refile:/etc/opendkim/TrustedHosts
